### ISSUE TITLE
3.10's "spaceship_targeting_advanced" missing from Layout Action Groups

### ISSUE THREAD

**Issue by Tsudico** [SCToolsfactory/SCJMapper-V2#100]
3.10 added a new section to the action map. Any bindings using the new section will not appear in the Layout dialog because the action groups are hard coded within ActionGroups.cs so "spaceship_targeting_advanced" should be added to line 45:
`x = new List<string>( ) { "spaceship_targeting", "spaceship_targeting_advanced", "spaceship_target_hailing", "spaceship_scanning", "spaceship_ping", "spaceship_radar" };`

I'm not sure if 3.10 added any other sections.

**Comment by bm98** [comment]
Yes need to add the new bindings of 3.10 and remove the ones CIG removed.
May take some time to catch up the never ending story...

**Comment by Tsudico** [comment]
Could you possibly make it so that the Layout groups are pulled in from a JSON file? That way people who aren't as involved could update it without waiting on the program to release a new version?

**Comment by bm98** [comment]
Usually I would take them from profile but then coloring is not possible. 
So yes a user file might be possible to have a non code change version.
I shall see - thanks for the hint.

**Comment by bm98** [comment]
OK - done see V2.48 Release
