### ISSUE TITLE
JoyStick trigger - Nothing shows up on the right panel

### ISSUE THREAD

**Issue by sutex** [SCToolsfactory/SCJMapper-V2#101]
When in SCJM and clicking my main trigger button nothing shows up on the right panel, and I do have it mapped in game, using a saved exported. Everyone other Joystick button mapped produces a result on the right panel except js1. So can't mapped or change whatever is assign to/on js1. What am I missing here?

**Comment by bm98** [comment]
Well, without any further information it is a bit hard to help...
I need to have the xml file that cause the trouble and also let me known which devices - go to Dump - Logfile and save this and attach it here - so I see what is where to map.

**Comment by sutex** [comment]
[DUMP_312.zip](https://github.com/SCToolsfactory/SCJMapper-V2/files/5753930/DUMP_312.zip)

**Comment by sutex** [comment]
Re-reading the above do you need my actual Profile .xml ?

**Comment by bm98** [comment]
Hmm, if you click any button on a device  - then nothing happens in the right panel anyway. 
The right panel changes if you Load a new map or if you DumpXML else it will never change.

The only thing that happens is if you use your JStick and have the the Tab Joystick 1 visible it would show js1_button1 in DevCtrl 
You would need to assign it to an action first and then Dump XML to have the right panel updated.
So I don't know where the issue would be.
Writing the steps you do would help. 
Right now I don't know if you start from an exported XML and want to redo some mappings or what ?

**Comment by sutex** [comment]
I start from an exported XML from SC and imported, using right click and open and import. Then click on the arrow pointing left which loads it into the Left panel.  Then click the tab 'All mapping' and check what's buttons are showing up green, assigned, for HOTAS. In the image below, everything green on the left and clicked on the Hotas, shows up in 'All mapping' on the right, except Js1_button1

**Below**
Mining Mode (Toggle_ js1_button5 show in 'All mapping' right panel. 
But, Fire Mining Laser (Toggle) js1_button1 does not.
![2021-01-01 02_05_37-SC Joystick Mapper](https://user-images.githubusercontent.com/10361359/103416374-53720d00-4bd6-11eb-9519-9c0638c3bbcc.png)

**Comment by smooreace** [comment]
You didnt hit buttom 1, so its not going to display button 1s action. You
hit button 2

**Comment by sutex** [comment]
Yes I did, read, the image is showing that the last button pushed is button 2 , Button 1 does not register, but is been clicked.

**Comment by smooreace** [comment]
Then read, I clearly said button 1 is not working in that case.

**Comment by sutex** [comment]
You have no idea what you are talking about smooreace you are just trolling, go way

**Comment by sutex** [comment]
There is nothing wrong with my Trigger (works everywhere else) Just js1_button1 does not register, in SCJM when clicked

**Comment by bm98** [comment]
does the button js1_button1 show up in the middle (Dev Ctrl field) ?
and does the button number show up as indicated below when pressed ?
![image](https://user-images.githubusercontent.com/7956007/103439603-9962bb80-4c3e-11eb-9981-1d5bf94d6917.png)

The one thing that makes buttons to not show up is when you disable them in Settings - like shown below:

![image](https://user-images.githubusercontent.com/7956007/103439625-ca42f080-4c3e-11eb-8dd4-4dfef2bd3659.png)

Here my button 1 is disabled and will only show as number in the Devices Tab but not in Dev Ctrl or otherwise.

So double check that there is no such thing in your Js2 stick

**Comment by sutex** [comment]
LOL .. Thanks heaps, there was this really invisible **1** in the Joystick one box . Problem solved No-idea how it got in there
