### ISSUE TITLE
"GamePad State" not zeroed - so a stick control action is always active for assignment

### ISSUE THREAD

**Issue by brookep1** [SCToolsfactory/SCJMapper-V2#29]
I have a Microsoft XBOX360 controller for Windows. Hardwired USB not wireless.

I've never used SC Joystick Mapper before so I might be missing a trick. But the GamePad state is always showing a value and doesn't "zero" when the sticks are centered. In the Device Tuning window I am able to get the sticks to zero (or a very small value) so I don't think it's a stuck sensor or my stick going bad. I've tried increasing the deadzone to see if that will squelch the GamePad State value but it doesn't.

With the "Ctrl." always showing one of the axis live it's difficult to map the buttons. Need to use the "Gamepad" mode so I can do the awesomeness that is multibutton mappings.

Is there a way to squelch the sensitivity on the gamepad state? Maybe use the same tuning curves to take deadzone value into account?

I haven't been able to figure out an external way to change the values before SC Joystick Mapper gets them.

![tuning_zeroed](https://cloud.githubusercontent.com/assets/8564483/7262135/4098555e-e845-11e4-9c29-5b4ccf4a96a9.PNG)
![not_zeroed](https://cloud.githubusercontent.com/assets/8564483/7262136/40992d76-e845-11e4-9bb4-9806c9478f50.PNG)

**Comment by brookep1** [comment]
Oh. I've tried both the latest release and the latest beta builds.

**Comment by bm98** [comment]
Hi,
I have an offset here as well but not that much. There is an option to decrease the sensitivity by increasing the detection limit.
You may find the file  SCJMapper.exe.config  along with the program. 
Open it with notepad and find the entry: gpSenseLimit="500"  
By increasing this number you may get more offset before the program assumes your gamepad stick is moved. The number is absolute - i.e. 500 handles + and -500.

Give it a try - well after edit you have to re-start the program to make it effective.
Also release the controls altogether and immediately (let them slip back) to have the best chance to maintain your intended control combination - the prog re-reads all controls every 0.5 sec so release must be within a rather short moment.

**Comment by bm98** [comment]
Hi,

Sorry for the late answer…

 

 

I have an offset here as well but not that much. There is an option to decrease the sensitivity by increasing the detection limit.

You may find the file SCJMapper.exe.config along with the program. 

 Open it with notepad and find the entry: gpSenseLimit="500"

 

By increasing this number you may get more offset before the program assumes your gamepad stick is moved. The number is absolute - i.e. 500 handles + and -500.

 

Give it a try - well after edit you have to re-start the program to make it effective.

Also release the controls altogether and immediately (let them slip back) to have the best chance to maintain your intended control combination - the prog re-reads all controls every 0.5 sec so release must be within a rather short moment.

 

Regs

Martin
