### ISSUE TITLE
Hello bm98 I want to show you this......

### ISSUE THREAD

**Issue by wolfrider66** [SCToolsfactory/SCJMapper-V2#30]
Hello bm98,

Your work on JSMapper is fantastic. So I wrote this: 
https://forums.robertsspaceindustries.com/discussion/258674/cassini-bm98-s-joystick-mapper#latest

  I am however having trouble with my pro flight Combat Rudder pedals working in game. I map my yaw to the Pedals and it seems to do that just fine inside JSMapper. But when I try the Device Tuning Yaw is not affected by my Pedals and in game Yaw is not affected by my pedals. 
  
  Unfortunately most PC related skills are over my head at this time. That is why I appreciate JSMapper so much. I am learning quickly however. I only recently retired from Professional Land Surveying so I have time now. Just let me know if you need a screen shot or a file attached and I will get that to you ASAP.

My PC:
X5960 Octa-core 3.0ghz CPU {Not Overclocked in any way}
Rampage V Extreme Motherboard
16GB RAM GDDR5
Titan Black 6GB GPU
RAID 0 250GB
5 Slot hotswap cage
2x2TB Hybrid Drives

Thanks for your time,

wolfrider66 (Here)
Oldwolf (Star Citizen)

**Comment by bm98** [comment]
Hi, appreciate your nice words :-)
Let's start from scratch so I may learn about the pedals - I don't have those so I cannot check it here ..

You may want go and find the file  log4net.config.OFF along the SCJMapper program and rename it to  log4net.config   i.e. removing the .OFF part

Then just start the program 
Make sure the pedals axis is mapped to "v_yaw"  - let me know what axis you use
then also go to Tuning, then back and exit.
There should be a log file   trace.log   created in the same place as the program is.
I would need this to see if any odd things are happening.
You can send this to cassini  at   burri-web.org or paste it here as answer (might be a bit long)

Then also we need to know where and what controls are known to the game :

Start the program again and...

Hit the 'Dump Log-->' button and just copy and paste from the right window
Here it looks like that:
-- 09.05.2015 23:31:08 - SC Joystick AC Log Controller Detection --
	<11:09:39> Log Started at 05/09/15 11:09:38
	<11:09:39> ProductVersion: 3.6.3.2654
	<11:09:40> Creating window called 'Star Citizen' (1584x1052)
	<11:09:41> Creating joystick1, vJoy Device
	<11:09:41> Creating joystick2, Saitek Pro Flight X-55 Rhino Stick

So I know that my X-55 would be on js2 - and I can set it up in SCJMapper if it does not match already

From here we may get further then.

Regs Martin

**Comment by wolfrider66** [comment]
Hi,I just got back from our Mother's Day dinner and it's a bit late so I will jump on this first thing tomorrow. Thanks for the reply,   James P Baldersonjamesbalderson@verizon.net  On 05/09/15, bm98<notifications@github.com> wrote: Hi, appreciate your nice words :-)Let's start from scratch so I may learn about the pedals - I don't have those so I cannot check it here ..You may want go and find the file  log4net.config.OFF along the SCJMapper program and rename it to  log4net.config   i.e. removing the .OFF partThen just start the program Make sure the pedals axis is mapped to "v_yaw"  - let me know what axis you usethen also go to Tuning, then back and exit.There should be a log file   trace.log   created in the same place as the program is.I would need this to see if any odd things are happening.You can send this to cassini  at   burri-web.org or paste it here as answer (might be a bit long)Then also we need to know where and what controls are known to the game :Start the program again and...Hit the 'Dump Log-->' button and just copy and paste from the right windowHere it looks like that:-- 09.05.2015 23:31:08 - SC Joystick AC Log Controller Detection --    11:09:39 Log Started at 05/09/15 11:09:38    11:09:39 ProductVersion: 3.6.3.2654    11:09:40 Creating window called 'Star Citizen' (1584x1052)    11:09:41 Creating joystick1, vJoy Device    11:09:41 Creating joystick2, Saitek Pro Flight X-55 Rhino StickSo I know that my X-55 would be on js2 - and I can set it up in SCJMapper if it does not match alreadyFrom here we may get further then.Regs Martin—Reply to this email directly or view it on GitHub.

**Comment by wolfrider66** [comment]
Well well well, this time it assigned JS2 to v_yaw: JS2_rotzwhen it was not working it was v_yaw: cntrl_JS2_rotz (or something very similar. I was not touching any control keys and I just thought that was how it's supposed to look)Also the tuning works as expected now. Does it have to do with turning the log4net.config to ON or did that just allow for the Trace log to be created? The latter I would guess.I have attached the Trace log which I renamed Trace_for_supportI will try the new profile "in-game" and see what is to be seen.Uh oh, "Houston we have a problem", I do not see JS2. Below is the Dump Log:-- 5/10/2015 11:28:25 AM - SC Joystick AC Log Controller Detection --    <22:36:59> Log Started at 05/08/15 22:36:57    <22:36:59> ProductVersion: 3.6.3.2654    <22:36:59> Creating window called 'Star Citizen' (1280x678)    <22:37:01> Creating joystick1, Saitek X52 Flight Controller Thank you for your time and have a super day, James P Baldersonjamesbalderson@verizon.net  On 05/09/15, bm98<notifications@github.com> wrote: Hi, appreciate your nice words :-)Let's start from scratch so I may learn about the pedals - I don't have those so I cannot check it here ..You may want go and find the file  log4net.config.OFF along the SCJMapper program and rename it to  log4net.config   i.e. removing the .OFF partThen just start the program Make sure the pedals axis is mapped to "v_yaw"  - let me know what axis you usethen also go to Tuning, then back and exit.There should be a log file   trace.log   created in the same place as the program is.I would need this to see if any odd things are happening.You can send this to cassini  at   burri-web.org or paste it here as answer (might be a bit long)Then also we need to know where and what controls are known to the game :Start the program again and...Hit the 'Dump Log-->' button and just copy and paste from the right windowHere it looks like that:-- 09.05.2015 23:31:08 - SC Joystick AC Log Controller Detection --    11:09:39 Log Started at 05/09/15 11:09:38    11:09:39 ProductVersion: 3.6.3.2654    11:09:40 Creating window called 'Star Citizen' (1584x1052)    11:09:41 Creating joystick1, vJoy Device    11:09:41 Creating joystick2, Saitek Pro Flight X-55 Rhino StickSo I know that my X-55 would be on js2 - and I can set it up in SCJMapper if it does not match alreadyFrom here we may get further then.Regs Martin—Reply to this email directly or view it on GitHub.

**Comment by wolfrider66** [comment]
Sorry for spamming you bm98, but I just sent my reply and looked back at JSMapper profile and it has changed to lcntrl+JS2_rotz  It still works in tuning because the assigned is still without the lcntrl tagAnd it appears I am using 2,13. I should upgrade to latest and greatest.  James P Baldersonjamesbalderson@verizon.net  On 05/09/15, bm98<notifications@github.com> wrote: Hi, appreciate your nice words :-)Let's start from scratch so I may learn about the pedals - I don't have those so I cannot check it here ..You may want go and find the file  log4net.config.OFF along the SCJMapper program and rename it to  log4net.config   i.e. removing the .OFF partThen just start the program Make sure the pedals axis is mapped to "v_yaw"  - let me know what axis you usethen also go to Tuning, then back and exit.There should be a log file   trace.log   created in the same place as the program is.I would need this to see if any odd things are happening.You can send this to cassini  at   burri-web.org or paste it here as answer (might be a bit long)Then also we need to know where and what controls are known to the game :Start the program again and...Hit the 'Dump Log-->' button and just copy and paste from the right windowHere it looks like that:-- 09.05.2015 23:31:08 - SC Joystick AC Log Controller Detection --    11:09:39 Log Started at 05/09/15 11:09:38    11:09:39 ProductVersion: 3.6.3.2654    11:09:40 Creating window called 'Star Citizen' (1584x1052)    11:09:41 Creating joystick1, vJoy Device    11:09:41 Creating joystick2, Saitek Pro Flight X-55 Rhino StickSo I know that my X-55 would be on js2 - and I can set it up in SCJMapper if it does not match alreadyFrom here we may get further then.Regs Martin—Reply to this email directly or view it on GitHub.
