### ISSUE TITLE
Steam Controller not detected

### ISSUE THREAD

**Issue by BrazilianJoe** [SCToolsfactory/SCJMapper-V2#33]
I have changed my default settings for the Steam Controller to have two joyticks to the left and right touchpads each. 

Being the default, they would be 'on' for all non-steam apps. 

The program has ' not detected any directinput devices'  though. 

I can help debug the issue if necessary.

**Comment by bm98** [comment]
Hi, had to first find out about this controller...
Seems from google that there is no straight way to use it outside of Steam. It emulates a kbd and mouse in the first place i.e. as HID devices that are not X- or D-Input devices.
There was one rept.  "..  i can confirm you can play non-steam games with it.
By adding them to your library as non-steam game, they can be accessed in big picture mode and, hereby, used with the steam controller." As I am not Steam playing at all I don't know if this is helpful?
For a Saitek one I created a bridge for an unsupported device (see the other repo here) .

Then there is News from 10.Dec:
"Steam users have also asked for the ability to use the controller to play games purchased on other services. The company will add the ability to program specific configurations for non-Steam games in an upcoming Steam beta client."

So I think there is not much the program can do about it but looking out for this support by Steam..
Sorry for not more help
Regs
