### ISSUE TITLE
Not all default actions editable in SCJM

### ISSUE THREAD

**Issue by Belatar** [SCToolsfactory/SCJMapper-V2#37]
Hi,

first of all many thanks for the awesome tool!

In version 2.18.0.51Beta it seems that not all possible actions are loaded from defaultProfile.xml.

Game version: 2.1.0d and 2.0.0

I set SCJM up with the correct path to game files (check box ticked), switched between public and test numerous times, removed all category filters, unticked "Mapped", did "Reset default/empty" several times.
But i.e. the keyboard binding of "v_throttle_100" or "v_throttle_zero" cannot be configured via the GUI. They do not appear in XML exports either. If I manually add them to the XML and try to grab them, they are as well not visible in the action list.

Pls help! Bela

**Comment by bm98** [comment]
Confirmed - don't know if it ever worked though
