### ISSUE TITLE
Deadzones values exported with "," instead of "."

### ISSUE THREAD

**Issue by Belatar** [SCToolsfactory/SCJMapper-V2#38]
Hi again,

in version 2.18.0.51Beta deadzones values for joysticks are exported with a "," instead of a "." so the game wont recognize the values.

Actual: 0,150
Expected: 0.150

Game version: 2.1.0d and 2.0.0

Thanks for the tool, kind regards, Bela

**Comment by bm98** [comment]
Seems to be the 'usual' Locale issue - if your locale (country) is using comas it may happen that the .Net formatting of numbers does it too but SC expects points.
I will change the program to not use locale settings for any formatting.
(we have dec.points so it did not cause issues here..)
