### ISSUE TITLE
Some unbindable keyboard/mouse buttons/axes

### ISSUE THREAD

**Issue by PhunkMaZ** [SCToolsfactory/SCJMapper-V2#40]
Hi,

there are some buttons or axes that cannot be bound to their corresponding devices. I.e. the rotateyaw or rotatepitch which cannot be bound to mouse-axis X or Y. Also the v_hud_open_scoreboard action cannot be bound to the tab-key as it's used to tab through UI of SCJMapper. Then i personally prefer to use one of my mouse-thumb-buttons to jump. But unfortunately "Button5" cannot be assigned to v_jump. 

Edit: Don't know if they have changed some names of the controls but from now on the default mouse names are:

kb1_maxis_x
kb1_maxis_y
kb1_mwheel_up
kb1_mwheel_down
kb1_mouse1
kb1_mouse2
kb1_mouse3
kb1_mouse4
kb1_mouse5
...

**Comment by bm98** [comment]
Hi,
for the TAB - yes does navigate, have added a context menu like the mouse ones to add it as mapping

for the unavailable mappings - if they are not available in the defaultProfile I cannot provide an entry either - sorry (e.g. v_jump is only available for kbd and pad)

Map names - just checked - it is really like:
  <action name="v_eject">
   <rebind input="mo1_mouse2"/>
  </action>

see next upload for the Tab fix
