### ISSUE TITLE
Uninstall Built-in Apps such as AAD.BrokerPlugin  

### ISSUE THREAD

**Issue by isaacscript** [SCToolsfactory/SCJMapper-V2#41]
Hello folks :  )
Either on CMD or PowerShell
What are commands to Uninstall Built-in apps such as AAD.BrokerPlugin!?
Thank you
<on Windows 10>

**Comment by bm98** [comment]
?? Seems to be part of Win10 - no relation to SCJMapper
I found this link:
http://www.experts-exchange.com/questions/28922751/Quick-Powershell-command-to-remove-unused-Microsoft-software-in-corporate-environment.html

but I have no idea what it is for nor if it is save to remove such stuff...
