### ISSUE TITLE
RumblePad 2 detected as Joystick

### ISSUE THREAD

**Issue by B4ckBone** [SCToolsfactory/SCJMapper-V2#42]
Hey there.
Nice software!

My old Rumblepad 2 is detected as a Joystick: Joy1
In the joystick settings there is one axis missing.
I have the left stick fully working.
The right stick is only working in the up down axis, which is mapped to Joy1 Z axis.
By default it is rolling left and right in the game.
Any chance to get my Rumblepad 2 with USB working?

Thanks for the good work. Keep it up!

---Edit--
I have the Gamepad tick box ticked.
But when i first opened the version 2.19 it was not ticked.
Maybe i need to reset something?
Bug 42 Hype ! :)
-- Edit end --

**Comment by bm98** [comment]
The gamepad is not enabled by default but if you check it once it should remain checked for further use
Though I did not thoroughly checked all pad functions ...
