### ISSUE TITLE
Pinkie switch support

### ISSUE THREAD

**Issue by jbinard** [SCToolsfactory/SCJMapper-V2#43]
First, thank you for this great software.

Do you plan to add support for the pinkie switch which allows to map multiple commands to a same button ?
Currently, it seems only possible with a profile configured in the saitek software for my X52.

**Comment by bm98** [comment]
Right now I see no way to do this - defining joystick button modifiers does not work.
Any hits how to achieve this?

**Comment by foumedia** [comment]
With my experience with the sainted, to use the pinkie modifier you simply have to go into the Saitek software and disable it as a "modifier button". Then it reverts to being a normal input button and acts like any jsx_button_20, etc. nothing on SCJ mappers end.

**Comment by jbinard** [comment]
I know how to use it as a simple button but my question was about using it as a modifier.
Unfortunatly, I have no idea if it's possible (it doesn't seem possible in Star Citizen).
The simplest way would be to map this to emulate a keypress but I don't know if it is possible in the XML.

**Comment by bm98** [comment]
Does not work to turn JS input into keyboard. May be CIG eventually let's us define JS modifiers but until then you have to use your Saitek software to do this.
