### ISSUE TITLE
.NET Framework errors on start and exit

### ISSUE THREAD

**Issue by Belatar** [SCToolsfactory/SCJMapper-V2#44]
Thanks for the update! But I run into .NET errors. Application does start after these errors, but input devices are not being recognized. I should see two joysticks, one from my Logitech G13, one Logitech 3D something. I added to screenshots, one from version 56, which runs ok and errorfree and one from version 57 with errors. Below the screenshots are the texts of the exceptions.

![scjm_56_ok](https://cloud.githubusercontent.com/assets/1206801/15626858/4d912df8-24d0-11e6-9a4c-68276f6eecfa.jpg)
![scjm_57_error](https://cloud.githubusercontent.com/assets/1206801/15626859/50a0222e-24d0-11e6-8b6f-9b1429ea4d6f.jpg)

Error 1:

System.FormatException: Der Index, basierend auf 0 (null), muss größer als oder gleich Null sein, und kleiner als die Größe der Argumentenliste.
   bei System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   bei System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   bei System.String.Format(String format, Object[] args)
   bei SCJMapper_V2.SC.SCPath.get_SCClientPath()
   bei SCJMapper_V2.SC.SCPath.get_SCClientUSERPath()
   bei SCJMapper_V2.SC.SCPath.get_SCClientMappingPath()
   bei SCJMapper_V2.SC.SCMappings.UpdateMappingNames()
   bei SCJMapper_V2.MainForm.LoadMappingDD()
   bei SCJMapper_V2.MainForm.MainForm_Load(Object sender, EventArgs e)
   bei System.Windows.Forms.Form.OnLoad(EventArgs e)
   bei System.Windows.Forms.Form.OnCreateControl()
   bei System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   bei System.Windows.Forms.Control.CreateControl()
   bei System.Windows.Forms.Control.WmShowWindow(Message& m)
   bei System.Windows.Forms.Control.WndProc(Message& m)
   bei System.Windows.Forms.Form.WmShowWindow(Message& m)
   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Geladene Assemblys **************
mscorlib
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1080.0 built by: NETFXREL3STAGE.
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll.
----------------------------------------
SCJMapper
    Assembly-Version: 2.23.0.57.
    Win32-Version: 2.23.0.57.
    CodeBase: file:///C:/Users/<User>/Downloads/SCJM/SCJMapper.exe.
----------------------------------------
log4net
    Assembly-Version: 1.2.13.0.
    Win32-Version: 1.2.13.0.
    CodeBase: file:///C:/Users/<User>/Downloads/SCJM/log4net.DLL.
----------------------------------------
System.Configuration
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1038.0 built by: NETFXREL2.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll.
----------------------------------------
System
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1081.0 built by: NETFXREL3STAGE.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll.
----------------------------------------
System.Core
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1038.0 built by: NETFXREL2.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll.
----------------------------------------
System.Xml
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1064.2 built by: NETFXREL3STAGE.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll.
----------------------------------------
System.Windows.Forms
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1038.0 built by: NETFXREL2.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll.
----------------------------------------
System.Drawing
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1078.0 built by: NETFXREL3STAGE.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll.
----------------------------------------
mscorlib.resources
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1038.0 built by: NETFXREL2.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_de_b77a5c561934e089/mscorlib.resources.dll.
----------------------------------------
System.Windows.Forms.resources
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1038.0 built by: NETFXREL2.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_de_b77a5c561934e089/System.Windows.Forms.resources.dll.
----------------------------------------
SharpDX.DirectInput
    Assembly-Version: 2.6.3.0.
    Win32-Version: 2.6.3.
    CodeBase: file:///C:/Users/<User>/Downloads/SCJM/SharpDX.DirectInput.DLL.
----------------------------------------
SharpDX
    Assembly-Version: 2.6.3.0.
    Win32-Version: 2.6.3.
    CodeBase: file:///C:/Users/<User>/Downloads/SCJM/SharpDX.DLL.
----------------------------------------

Error 2:

System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei SCJMapper_V2.MainForm.MainForm_Activated(Object sender, EventArgs e)
   bei System.Windows.Forms.Form.OnActivated(EventArgs e)
   bei System.Windows.Forms.Form.set_Active(Boolean value)
   bei System.Windows.Forms.Form.WmActivate(Message& m)
   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Geladene Assemblys **************
mscorlib
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1080.0 built by: NETFXREL3STAGE.
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll.
----------------------------------------
SCJMapper
    Assembly-Version: 2.23.0.57.
    Win32-Version: 2.23.0.57.
    CodeBase: file:///C:/Users/<User>/Downloads/SCJM/SCJMapper.exe.
----------------------------------------
log4net
    Assembly-Version: 1.2.13.0.
    Win32-Version: 1.2.13.0.
    CodeBase: file:///C:/Users/<User>/Downloads/SCJM/log4net.DLL.
----------------------------------------
System.Configuration
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1038.0 built by: NETFXREL2.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll.
----------------------------------------
System
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1081.0 built by: NETFXREL3STAGE.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll.
----------------------------------------
System.Core
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1038.0 built by: NETFXREL2.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll.
----------------------------------------
System.Xml
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1064.2 built by: NETFXREL3STAGE.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll.
----------------------------------------
System.Windows.Forms
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1038.0 built by: NETFXREL2.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll.
----------------------------------------
System.Drawing
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1078.0 built by: NETFXREL3STAGE.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll.
----------------------------------------
mscorlib.resources
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1038.0 built by: NETFXREL2.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_de_b77a5c561934e089/mscorlib.resources.dll.
----------------------------------------
System.Windows.Forms.resources
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1038.0 built by: NETFXREL2.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_de_b77a5c561934e089/System.Windows.Forms.resources.dll.
----------------------------------------
SharpDX.DirectInput
    Assembly-Version: 2.6.3.0.
    Win32-Version: 2.6.3.
    CodeBase: file:///C:/Users/<User>/Downloads/SCJM/SharpDX.DirectInput.DLL.
----------------------------------------
SharpDX
    Assembly-Version: 2.6.3.0.
    Win32-Version: 2.6.3.
    CodeBase: file:///C:/Users/<User>/Downloads/SCJM/SharpDX.DLL.
----------------------------------------

Error 3:

System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei SCJMapper_V2.MainForm.MainForm_Activated(Object sender, EventArgs e)
   bei System.Windows.Forms.Form.OnActivated(EventArgs e)
   bei System.Windows.Forms.Form.set_Active(Boolean value)
   bei System.Windows.Forms.Form.WmActivate(Message& m)
   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Geladene Assemblys **************
mscorlib
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1080.0 built by: NETFXREL3STAGE.
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll.
----------------------------------------
SCJMapper
    Assembly-Version: 2.23.0.57.
    Win32-Version: 2.23.0.57.
    CodeBase: file:///C:/Users/<User>/Downloads/SCJM/SCJMapper.exe.
----------------------------------------
log4net
    Assembly-Version: 1.2.13.0.
    Win32-Version: 1.2.13.0.
    CodeBase: file:///C:/Users/<User>/Downloads/SCJM/log4net.DLL.
----------------------------------------
System.Configuration
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1038.0 built by: NETFXREL2.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll.
----------------------------------------
System
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1081.0 built by: NETFXREL3STAGE.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll.
----------------------------------------
System.Core
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1038.0 built by: NETFXREL2.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll.
----------------------------------------
System.Xml
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1064.2 built by: NETFXREL3STAGE.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll.
----------------------------------------
System.Windows.Forms
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1038.0 built by: NETFXREL2.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll.
----------------------------------------
System.Drawing
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1078.0 built by: NETFXREL3STAGE.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll.
----------------------------------------
mscorlib.resources
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1038.0 built by: NETFXREL2.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_de_b77a5c561934e089/mscorlib.resources.dll.
----------------------------------------
System.Windows.Forms.resources
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1038.0 built by: NETFXREL2.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_de_b77a5c561934e089/System.Windows.Forms.resources.dll.
----------------------------------------
SharpDX.DirectInput
    Assembly-Version: 2.6.3.0.
    Win32-Version: 2.6.3.
    CodeBase: file:///C:/Users/<User>/Downloads/SCJM/SharpDX.DirectInput.DLL.
----------------------------------------
SharpDX
    Assembly-Version: 2.6.3.0.
    Win32-Version: 2.6.3.
    CodeBase: file:///C:/Users/<User>/Downloads/SCJM/SharpDX.DLL.
----------------------------------------

**Comment by bm98** [comment]
I see the issue – however there is something strange.

Basic issue was a formatting bug. But this should only hit when the SC path cannot be found (which should not be the case I assume as 2.22 run well)

Anyhow I included a preview for 2.24 Build 58 which gets rid of the errors but I am still a bit concerned by the SC path thing.

If you could check and report would be helpful

Regs Martin

**Comment by Belatar** [comment]
Strange, I get the following error message when opening the program.

![image](https://cloud.githubusercontent.com/assets/1206801/15628230/45ec82e2-24fc-11e6-8085-45cb9a363275.png)

I tried with normal access and admin access. The correct path was already configured in the settings, but it still didn't find it. I set the path again but still the same error message.

Possible language issue? I run german Windows 10. Or maybe shell variables issue?

**Comment by bm98** [comment]
Hi 

 

Hmm – should not be a language issue (have German here as well…)

Then Win10 I don’t know – it is the same as Win7 for those topics.

 

But I have a pretty old installation here as reference and don’t know all CIG updates regarding installation.

Mine is also not in the Win System folders but on a different disk- so I may not see all possibilities to find things..

 

Usually one cannot put User Files into the Windows Program Files path at all.

So it looks like the installation is different when done more recently or into the Windows folders.

 

Could you help me to find the path then?

 

I would look for the following (full path needed or a screenshot of the structure):

a)      Where are the game datafiles e.g. the file  somewhere\DataXML.pak  (here I pull the defaultProfile.xml)

b)      Where are the USER  files located e.g.  Somewhere\StarCitizen\Public\USER
i.e. where the mapping file would need to go  i.e.   ..\USER.\Controls\Mappings

 

I may try to install in on my Win10 Test machine but this takes a while as I need to DL the 20Gigs first…

 

Regs und Danke..

**Comment by Belatar** [comment]
DataXML.pak: C:\Program Files\Cloud Imperium Games\StarCitizen\Test\Data\

Mappings: C:\Program Files\Cloud Imperium Games\StarCitizen\Test\USER\Controls\Mappings\

I would guess that permissions might be the issue, as these folders require admin access. Could it be the older versions never actually tried to access these folders and circumvented the error? I always manually copied my mapping files over.

**Comment by bm98** [comment]
Thanks, there was no change in actually accessing any of the files in this build.Only to find the path to them - which seems to be off.
The prog only reads  DataXML.pak (should not be a problem)
Then I write the maps to the Mappings folder and the backup location (but may be not checked for errors - need to see)
However the Test\something  folders relate to PTU mode only (needs to be setup in Settings) otherwise it looks for ...\Public\..  or ...Live\..  (Live was new in this build)
Would it be possible to enable the debug log
i.e. besides the SCJmapper.exe is log4net.config.OFF  - just remove .OFF and rerun the application and the get the file  trace.log  and may be zip and attach it here.
There are traces of what works and what not - may be I can find something.

**Comment by Belatar** [comment]
There you go...

[trace.zip](https://github.com/SCToolsfactory/SCJMapper-V2/files/288001/trace.zip)

**Comment by bm98** [comment]
At least one problem found...
the path you enter in Settings should be the one where CIGLauncher.exe is 

from the Log - user defined folder given: C:\Program Files\Cloud Imperium Games\StarCitizen
Now this is one StarCitizen too much - this is already one down.

I did Setup SC on my Win10 with German Win10 and it could find it automatically and when I used 
C:\Program Files\Cloud Imperium Games   it also worked (should not be permissions - at least not for reading)

First I'd try with no manual entry and see if it is going to work, (just uncheck the option)
But then you need to have only "C:\Program Files\Cloud Imperium Games" in to try the manual path

**Comment by Belatar** [comment]
Cool, unchecking the "Path" in settings did the trick, no errors anymore. Thanks for helping!
