### ISSUE TITLE
Last control assigned appears as current after changing action

### ISSUE THREAD

**Issue by d3gs** [SCToolsfactory/SCJMapper-V2#49]
Procedure: Assign any control to an action. Select another action at left menu. Will show at Mapping Area current selected command and last assigned control. After click on Clear still shows last assinged control.
Expected: Show current assigned control or blank if clear.
BTW very nice program. Thank you.

**Comment by pyrewyrm** [comment]
Known thing but it would be nice to see the assigned value rather than last value used.

**Comment by bm98** [comment]
Seems I found a rather working solution...
Lets wait for some more testing of Build 62 as it contains some more difficult additions..

**Comment by xorozov** [comment]
Hi ! cant get the yaw working in the game. in the sc mapper its read as rotz, seems fine, but in game it does nothing. Thanks for comments suggestions

**Comment by bm98** [comment]
Improved in V 2.28
