### ISSUE TITLE
Yaw function does not work in game

### ISSUE THREAD

**Issue by xorozov** [SCToolsfactory/SCJMapper-V2#50]
Hi, 
An issue with yaw function within the game. Ive made the input in the SCJMapper and succesfully dumped and saved (Rudder input is visible in the mapper program). Imported within the game (also via console). During play, the yaw(Rudder) function is not working, tried several times. 
Please suggest anything!?
Thank you 
using defender cobra m5 joystick

**Comment by bm98** [comment]
Try.. get the default mappings in the game and map the yaw function in the game.
Then Export it in the game - you find the export in the Mapping folder.
Try if it works in game then.
Then compare the one from SCJMapper and the one exported and let me know about the delta - or attache the files here - see if we can find out where it fails.
