### ISSUE TITLE
Exception reading defaultProfile in SC PTU2.6.2

### ISSUE THREAD

**Issue by bm98** [SCToolsfactory/SCJMapper-V2#51]
The defaultProfile.xml carries twice the actionmap multiplayer - prog breaks with Key already in collection when reading the second multiplayer map.

**Comment by bm98** [comment]
I expect CIG to remove the second entry at some point in time as it is a bug in the profile.
But it will be fixed in an upcoming version to no longer break on the second one but ignore it.

**Comment by bm98** [comment]
**Workaround** until the next version is ready

to allow the current version to start - download the linked defaultProfile.txt and put it into the folder where the application is. 
 
--> THEN REMOVE the file extension to have it named only   **defaultProfile** 

Start SCJMapper - and it should work again.

The profile provided is from the 2.6.2 version where I removed the second multiplayer actionmap.


[defaultProfile.txt](https://github.com/SCToolsfactory/SCJMapper-V2/files/894024/defaultProfile.txt)

**Comment by iNgeon** [comment]
Busy downloading 2.6.3 hope it still works :-)

**Comment by bm98** [comment]
defaultProfile of 2.6.3 is exactly the same as in 2.6.2
So the workaround should still work....
