### ISSUE TITLE
mouse buttons 4 and above are not supported

### ISSUE THREAD

**Issue by jsimon1080** [SCToolsfactory/SCJMapper-V2#52]
If you have an entry like this in the XML file...

		<action name="jump">
			<rebind input="mo1_mouse4"   />
		</action>

It works in game, but SCJMapper does not recognize it.

Keep up the good work and thanks a lot for the fix to make it work with 2.6.2!

**Comment by bm98** [comment]
strange it works in game..

snip from defaultProfile 2.6.3

<action  name="jump"  onPress="1"  keyboard="space" ...

the only jump in the defaultProfile is available for kbd only - so the program is not able to map it.
Sorry
BTW mouse1 ..mouse8 is supported and works if the entry is available in defaultProfile

**Comment by bm98** [comment]
actions that are not in the defaultProfile defined are not available even if the game accepts them
