### ISSUE TITLE
unhandled exception when opening program or attempting to save/load xml's

### ISSUE THREAD

**Issue by Freebirth** [SCToolsfactory/SCJMapper-V2#53]
upon startup or when attempting to grab/dump/load/or save an .xml i get an unhandled exception. this is the detail for the error on startup.  this happens with every version of scjmapper i have tried. 

> See the end of this message for details on invoking 
> just-in-time (JIT) debugging instead of this dialog box.
> 
> ************** Exception Text **************
> System.NullReferenceException: Object reference not set to an instance of an object.
>    at SCJMapper_V2.ActionTree.LoadProfileTree(String defaultProfileName, Boolean applyDefaults)
>    at SCJMapper_V2.MainForm.InitActionTree(Boolean addDefaultBinding)
>    at SCJMapper_V2.MainForm.InitDirectInput()
>    at SCJMapper_V2.MainForm.MainForm_Load(Object sender, EventArgs e)
>    at System.Windows.Forms.Form.OnLoad(EventArgs e)
>    at System.Windows.Forms.Form.OnCreateControl()
>    at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
>    at System.Windows.Forms.Control.CreateControl()
>    at System.Windows.Forms.Control.WmShowWindow(Message& m)
>    at System.Windows.Forms.Control.WndProc(Message& m)
>    at System.Windows.Forms.Form.WmShowWindow(Message& m)
>    at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
> 
> 
> ************** Loaded Assemblies **************
> mscorlib
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.6.1637.0 built by: NETFXREL3STAGE
>     CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
> ----------------------------------------
> SCJMapper
>     Assembly Version: 2.27.0.61
>     Win32 Version: 2.27.0.61
>     CodeBase: file:///C:/Users/Freebirth/Desktop/SCJMapper-V2.27Build61/SCJMapper.exe
> ----------------------------------------
> log4net
>     Assembly Version: 1.2.13.0
>     Win32 Version: 1.2.13.0
>     CodeBase: file:///C:/Users/Freebirth/Desktop/SCJMapper-V2.27Build61/log4net.DLL
> ----------------------------------------
> System.Configuration
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.6.1586.0 built by: NETFXREL2
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
> ----------------------------------------
> System
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.6.1637.0 built by: NETFXREL3STAGE
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
> ----------------------------------------
> System.Core
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.6.1638.0 built by: NETFXREL3STAGE
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
> ----------------------------------------
> System.Xml
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.6.1586.0 built by: NETFXREL2
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
> ----------------------------------------
> System.Windows.Forms
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.6.1586.0 built by: NETFXREL2
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
> ----------------------------------------
> System.Drawing
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.6.1586.0 built by: NETFXREL2
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
> ----------------------------------------
> SharpDX.DirectInput
>     Assembly Version: 2.6.3.0
>     Win32 Version: 2.6.3
>     CodeBase: file:///C:/Users/Freebirth/Desktop/SCJMapper-V2.27Build61/SharpDX.DirectInput.DLL
> ----------------------------------------
> SharpDX
>     Assembly Version: 2.6.3.0
>     Win32 Version: 2.6.3
>     CodeBase: file:///C:/Users/Freebirth/Desktop/SCJMapper-V2.27Build61/SharpDX.DLL
> ----------------------------------------
> SharpDX.XInput
>     Assembly Version: 2.6.3.0
>     Win32 Version: 2.6.3
>     CodeBase: file:///C:/Users/Freebirth/Desktop/SCJMapper-V2.27Build61/SharpDX.XInput.DLL
> ----------------------------------------
> Ionic.Zip.Reduced
>     Assembly Version: 1.9.1.8
>     Win32 Version: 1.9.1.8
>     CodeBase: file:///C:/Users/Freebirth/Desktop/SCJMapper-V2.27Build61/Ionic.Zip.Reduced.DLL
> ----------------------------------------
> 
> ************** JIT Debugging **************
> To enable just-in-time (JIT) debugging, the .config file for this
> application or computer (machine.config) must have the
> jitDebugging value set in the system.windows.forms section.
> The application must also be compiled with debugging
> enabled.
> 
> For example:
> 
> <configuration>
>     <system.windows.forms jitDebugging="true" />
> </configuration>
> 
> When JIT debugging is enabled, any unhandled exception
> will be sent to the JIT debugger registered on the computer
> rather than be handled by this dialog box.

**Comment by faybs** [comment]
Happening here as well. Running 64 bit Windows 10 with all the latest patches.

**Comment by Freebirth** [comment]
oh yeah, guess i should say i am aldobon windows 10 64 bit, everything up to date. and running in administrator mode doesnt change anything.

**Comment by Freebirth** [comment]
aldobon = also on..... dumb phone screen

**Comment by bm98** [comment]
Check this one out:

 

 <https://github.com/SCToolsfactory/SCJMapper-V2/issues/51> https://github.com/SCToolsfactory/SCJMapper-V2/issues/51

 

The Workaround described should help

 

Regs

**Comment by Freebirth** [comment]
this does fix it, in win!)_ make sure to click view int he folder and check the option to show file extensions.

**Comment by bm98** [comment]
Same as issue #51
