### ISSUE TITLE
Microsoft .NET Framework error

### ISSUE THREAD

**Issue by G0rfik** [SCToolsfactory/SCJMapper-V2#54]
This is the error I get when starting SCJ mapper. My OS is w10 microsoft net framework up to date. https://gyazo.com/36ee90af8c36ea03141ac8dc51775398

**Comment by bm98** [comment]
Check this one out:

 

 <https://github.com/SCToolsfactory/SCJMapper-V2/issues/51> https://github.com/SCToolsfactory/SCJMapper-V2/issues/51

 

The Workaround described should help

 

Regs

**Comment by bm98** [comment]
Same as issue #51
