### ISSUE TITLE
SCJMapper-V2.28Build62 Exception on Options & Device Tuning

### ISSUE THREAD

**Issue by iNgeon** [SCToolsfactory/SCJMapper-V2#56]
When clicking on Options or Device Tuning it throws the following exception.

https://pastebin.com/guAc43eY

at SCJMapper_V2.MainForm.btJSTuning_Click(Object sender, EventArgs e)
&
at SCJMapper_V2.MainForm.btOptions_Click(Object sender, EventArgs e)

Windows 7 SP1, Logitech Extreme 3D Pro, SC 2.6.3

**Comment by bm98** [comment]
Yes - found it
and yes there are some other issues mostly with gamepads as well ...
Will be fixed for the next update
Meanwhile try to map all 3 directions before Tuning.
