### ISSUE TITLE
SCJ Mapper Question?

### ISSUE THREAD

**Issue by MaxSharp** [SCToolsfactory/SCJMapper-V2#57]
Love, love, love the SCJ Mapper!  Definitely solves the problem of having your keymapping 'wiped' after each SC update (and after a corruption of your USER folder).

I have about 90% of my keys/joystick controls entered, but my question is....

Under the Action Menu, I'm trying to bind the 'Use' button to work with my Mouse/Button 4. Since it does not have a 'Mouse Icon' listed next to the 'Use' function within the Action Tree (only a Keyboard Icon), is there a way to add a Mouse Function?  The SCJ Mapper .pdf file/instructions leads me to believe I'm able to do this?

More specifically, when I select the 'Use' function from the Action Tree, I switch to JS/Kbd and right click over the Ctrl Box and it allows me to select Mouse Button 4 (i.e. mo1_mouse4).  However, when I select 'Assign', it does NOT save the mouse function under the Action Tree?  Am I missing something?

Any help would be greatly appreciated!

~MaxSharp

**Comment by bm98** [comment]
Hi Max,

glad you like it :)

 

for the “use” the default profile lists the following:

 

<action  name="use"  onPress="1"  onRelease="1"  keyboard="f"  xboxpad="y"

 

And therefore the Action tree gets you only Kbd and Gamepad as icon. That you can select mouse from the Kbd entry is merely a shortcut on my side to not have another entry for the mouse only.

The prog checks if the assignment matches and ignores impossible ones.

I.e. a joystick entry cannot be assigned to a Kbd – same is with a mouse entry.

 

However…. I just went into the game and assigned the mouse button in Options-Keybindings as follows – replacing the f assignment for two items which are the exported settings from the game

 

<actionmap name="player">

  <action name="use">

   <rebind input="mo1_mouse4"/>

  </action>

 

<actionmap name="vehicle_general">

  <action name="v_exit">

   <rebind input="mo1_mouse4"/>

  </action>

 

And in the hangar I could no longer use f to enter the buggy but my mouse button 4 and to leave I had to press – long – button 4 again same as previously with the keyboard f

 

So it seems that there is more possible than what one can see in the default profile. And CIG always handles keyboard/mouse in the same setting tab – could be that the mapping is not restrictive as it looks from a distance…

 

I may have try some of those manually and then allow for this if things are working – especially mapping the keyboard and a mouse button would be helpful then.

 

Regs

Martin
