### ISSUE TITLE
2.30 Build 64 Won't launch - "Initializing DirectXInput failed - program exits now"

### ISSUE THREAD

**Issue by gkleinfe** [SCToolsfactory/SCJMapper-V2#59]
I'm getting the error in the title when I try to launch the app.  Here is a copy of the trace.log renamed so I could attach it.

[trace.txt](https://github.com/SCToolsfactory/SCJMapper-V2/files/1252543/trace.txt)

Windows 10 (64 bit)
Radeon RX 480

Connected Game Controllers
Saitek x56 Stick
Saitek x56 Throttle
Logitech G27 Racing Wheel and Pedals

**Comment by gkleinfe** [comment]
One more piece of information.  I'm using remote desktop to access my game PC from work to test this software.  Does remote desktop use some sort of virtual mouse driver that is causing the problem? 

I'll wait until I get home and test again.

**Comment by gkleinfe** [comment]
That was precisely the problem.  If I remote in to my PC, Windows must use a virtual mouse driver to allow for control.  The software did not account for this type of device and generated the error.

It works just fine when log in locally.

**Comment by bm98** [comment]
Seems the DirectX Wrapper I use - DXSharp does not handle the virtual mouse properly as it raises a DXSharp exception.
Would be hard to circumvent without rewriting a lot of code.
Hope the program is still usable for you.
