### ISSUE TITLE
PTU 3.0 defaultProfile and how to use it - Information for users

### ISSUE THREAD

**Issue by bm98** [SCToolsfactory/SCJMapper-V2#62]
[defaultProfile-PTU-3-20171202.zip](https://github.com/SCToolsfactory/SCJMapper-V2/files/1524424/defaultProfile-PTU-3-20171202.zip)

If you want to use SCJMapper with PTU 3.0 you may need the current defaultProfile.xml and some advice how to use it....
Get the above zip file and follow the README.txt

Please let this issue open for a while to update the file if needed

**Comment by bm98** [comment]
[defaultProfile-PTU-3-20171214.zip](https://github.com/SCToolsfactory/SCJMapper-V2/files/1563604/defaultProfile-PTU-3-20171214.zip)

Update from PTU Update - defaultProfile as of Dec 14, 2017
Get the above zip file and follow the README.txt

**Comment by OrphuesRocker** [comment]
Thanks for updating the default profile. There doesn't seem to any variables for missiles. Is this something I've done? Thanks for your help.

**Comment by OrphuesRocker** [comment]
My bad. There are no keyboard actions for the missiles. Please disregard my earlier comment.

**Comment by bm98** [comment]
[defaultProfile-PTU-3-20171215.zip](https://github.com/SCToolsfactory/SCJMapper-V2/files/1564777/defaultProfile-PTU-3-20171215.zip)

Update from PTU Update - defaultProfile as of Dec 15, 2017 (PTU 689345)
Get the above zip file and follow the README.txt

**Comment by bm98** [comment]
[defaultProfile-PTU-3-20171218.zip](https://github.com/SCToolsfactory/SCJMapper-V2/files/1572658/defaultProfile-PTU-3-20171218.zip)

Update from PTU Update - defaultProfile as of Dec 18, 2017 (PTU 691578)
Get the above zip file and follow the README.txt

**Comment by bm98** [comment]
No need for this one - defaultProfile is taken from p4k file since last release
