### ISSUE TITLE
Cannot find SC path - Non-Standard install

### ISSUE THREAD

**Issue by Timbleweed** [SCToolsfactory/SCJMapper-V2#65]
My game path is F:\Games\Roberts Space Industries\StarCitizen

**Comment by bm98** [comment]
Hi,  pls check if the Check Box Left of  the Path in settings is checked – else it is not used

Then make sure you point to the folder where RSI Launcher and StarCitizen is located

You may need only  F:\Games\Roberts Space Industries – looks like you went one too deep

 

Regs
