### ISSUE TITLE
Mappings for Ground Vehicle are missing/get erased

### ISSUE THREAD

**Issue by aschoonewolff** [SCToolsfactory/SCJMapper-V2#66]
First of all, thanks a lot for this wonderful program!!

On 3.0 is it possible to assign mappings to Ground Vehicles, there are currently 3 categories:
Ground Vehicle - General
Ground Vehicle - Movement
Ground Vehicle - Gunner
And in the exported files under:
`<actionmap name="vehicle_general"></actionmap>`
`<actionmap name="vehicle_driver"></actionmap>`

These are not possible to map in the SCJMapper tool. The problem is not so much as they are not mappable, but that if they are setup in-game, and the profile is exported and loaded into SCJMapper, then modified and dumped again, it erases the manual mappings, which is a bit annoying.

**Comment by bm98** [comment]
Hi,

 

should be possible I can see them here

 – you may need to go to Config-Settings and Unhide the actionmaps (remove the checkmark); some are default off (may be I have to change this once…)

 

Regs

**Comment by aschoonewolff** [comment]
Aha! My bad, did not realize those mappings were disabled by default. Enabling them works like a charm!
