### ISSUE TITLE
Detected axis not recognised in game

### ISSUE THREAD

**Issue by rishp** [SCToolsfactory/SCJMapper-V2#68]
Hi,

Firstly, I'd like to thank you for this awesome tool and the quick start guide.

Here's my "issue" your tool recognises my pedal when pressed as js1_slider2, that bit's fine. When I'm in-game js1_slider2 isn't recognised, I press the pedal in the keybind option but it doesn't detect it and the axis doesn't appear in the dead zone options. Do you have any thoughts what's going on here? Is the game mapper just not detecting the axis but your tool is?

**Comment by bm98** [comment]
Is there any Controller Software running which remaps controls when a certain game (e.g. SC) is active.
If you have a device manufacturers software for the pedal - may be try to default it - That is the only thing I can think of. My tool uses plain DirectInput detection which is the same interface SC uses (I think...). Other than that sliders can possibly only assigned to analog commands such as Pitch, Yaw etc.
Or try to google for your device and issue - don't know if someone else found how to use it?

**Comment by rishp** [comment]
I ended up using vjoy to map slider2 which also has a beneficial side-effect of being able to map two separate controller inputs on the same pedal depending on how far a press the pedal down during mapping.
