### ISSUE TITLE
Problem with Chat / Enter key mapping

### ISSUE THREAD

**Issue by aschoonewolff** [SCToolsfactory/SCJMapper-V2#69]
Hi, 

I am not sure where this is coming from, it might as well be something related to the game. 
But now, every time I create a binding file from SCJMapper, the chat will not work properly in SC. Pressing F12 shows the chat, but the key enter only works once the Focus is in the Chat, after that pressing enter does not send the message (or make the field disappear if its empty). On the other hand the NumPad enter works without any problem. It seems it's mixing up Enter and NumEnter.

**Comment by bm98** [comment]
Are you mapping kb1_enter somehow?

the chat has it's defaults (from default profile)

<action  name="focus_on_chat_textinput"  onPress="1"   >
			<keyboard  >
				<inputdata  input="enter"  />
				<inputdata  input="np_enter"  />
			</keyboard>
```
So if you don't overwrite enter somehow it should not be affected by any other mapping.

May be double check the created mapping file for kb1_enter   and then also see if that 'focus_on_chat_text_input' is not overwritten either.
Other than that  - the mapping created by the program should not really interfere with the defaults or at least not intentionally - but we do not really know how CIG does things....

**Comment by aschoonewolff** [comment]
I have the following XML code from the generated file by SCJMapper (related to kb1_enter):

`
<action name="pl_hud_confirm">
     <rebind input="kb1_enter"   />
</action>
`
`
<action name="focus_on_chat_textinput">
     <rebind input="kb1_enter"   />
</action>
`

But I have not explicity mapped the enter key at all, just joystick inputs.

**Comment by bm98** [comment]
May be you have mapped a lot of the defaults for whatever reason.
If you Load.. with Reset, Load & Grab you can see what the created profile contains (everything else comes with the CIG defaults). Then may be remove 'Clear' the ones where the enter key is mapped.
And save as a new mapping file and try if things get better ??

I do usually leave the default mappings from CIG alone unless they don't fit me - then I either remap them somewhere else or 'Disable' them if I don't want to use them either.
The problem with remapping some defaults is that CIG uses ActionModes which change the press, release behavior in the defaultProfile and if you miss those in the remapping it will not work as expected.

**Comment by aschoonewolff** [comment]
So I have been trying to reproduce this from a blank and default configuration, to no avail. So this is definitely not a bug on your side. Something in SC messed up the configuration, whatever that was I do not know. Have fixed it by removing the <rebind>, and problem does not appear on any of the new profiles. Closing this down.
