### ISSUE TITLE
All commands

### ISSUE THREAD

**Issue by d2bishop** [SCToolsfactory/SCJMapper-V2#71]
Have all commands available for all mappings of joysticks.
'prone' name change to 'on foot - all' and add all the commands under that heading.
'scanning' needs joystick control for use in a Terrapin turret, not sure about this have not tried it out yet.
There might be others that I have not found.

Trying to keep the switching from joysticks to keyboard and mouse at a minimum.

Thanks for reading

**Comment by bm98** [comment]
In general the commands taken from the defaultProfile and not set via the program - so either it is there or not.
However the command names depends on whether you use the original profile names or the ones from the CIG translation - can be set in Settings (also described in the Quickguide)
i.e. Engl. translated "Prone" is in the actionmap "On Foot - All" is the same as in the profile "prone" in the actionmap "player".
So you choose which one you prefer.
