### ISSUE TITLE
Controls not working right for me

### ISSUE THREAD

**Issue by d2bishop** [SCToolsfactory/SCJMapper-V2#72]
OS Windows 7 pro, CH Products FIGHTERSTICK and Pro Throttle
Throttle is listed as Joystick 1 and FIGHTERSTICK is listed as joystick 2
For this I did not load "Control Manager PC Programming Software V 4.55a" just used Windows 7 drivers.

Started from a default layout.
See Map 1.jpg 
Used Joystick 2, button9 for "v_view_yaw_left" in green outline
Used Joystick 1, button9 for "v_view_yaw_right" in blue outline
 Have different commands for each view.
![map 1](https://user-images.githubusercontent.com/37783091/40385505-511a2fd6-5df6-11e8-98ce-8f9e0f9238d1.jpg)

After clicking Mappings / selecting "layout_keyboard_advanced"  / clicking Load... / clicking Load and Grab !
See Map 2.jpg
Used Joystick 2, button9 for "v_view_yaw_left" in green outline
Used Joystick 1, button9 for "v_view_yaw_right" in blue outline
Have the same command for each view.
Do not know what the jsx is, but it seems to combine the 2 joysticks.
![map 2](https://user-images.githubusercontent.com/37783091/40385531-6811ae44-5df6-11e8-9b9d-707f0236ea18.jpg)

I would like to use the advanced keyboard layout without entering all the commands by hand.

What am I doing wrong?
Thanks for your help

**Comment by d2bishop** [comment]
I did a Dump and Save at end of day, this is the file;
[layout_my_standard.txt](https://github.com/SCToolsfactory/SCJMapper-V2/files/2031126/layout_my_standard.txt)
Started my PC and opened SCJMapper.exe this is what it opened to;
![map 3](https://user-images.githubusercontent.com/37783091/40427182-8123d1aa-5e8c-11e8-91d6-58fe9a340535.jpg)

It looks like SCJMapper has combined the 2 joysticks as one during the shutdown.
So when I enter a new control I get this;
![map 4](https://user-images.githubusercontent.com/37783091/40427377-0c6d46e2-5e8d-11e8-9ebf-cd8647510e7a.jpg)

**Comment by d2bishop** [comment]
I might have found a work around, will check later if it repeats.
Have do some stuff with the wife.

**Comment by d2bishop** [comment]
Oops I just realized that the last time was with the CH Products software installed.
doing more testing

**Comment by bm98** [comment]
Well I try to follow your path and have a hint on how to proceed in your case:

To get the advanced_kbd and some of your bindings but NOT all other defaults into a file it is:
a) Reset  - Empty,
b) Mappings: Select "layout_keyboard_advanced"
c) Load - Load ...   > now you have the complete advanced map in the XML window
d) Grab XML  > now the formerly empty tree should have the advanced commands inserted
e) Assign your joystick devices with a number to get the js1_, js2_ designation
  Config - Js Reassign Dialog  > change the n.a. items to a number usually the first would be js1 and the second js2   - I think missing this one caused your jsx_ trouble
f) Dump XML  > this extends the XML file with the joystick assignment and adds some other needed stuff to the file.
You may save here to have just the advanced with your chosen name in the proper format.

From here you may add more manually and then Dump & Save again ...

Note: If you start with Reset - Defaults you always get the big XML that includes all from CIG default mappings - but this is essentially useless and some rebinds there may even disrupt the normal behavior as the created XML for rebind is not that specific as some of the defaultProfile bindings are - hence better not...

jsx_  is always there when you start the program as you have not pressed or moved any of the joysticks and the programs does not know better and therefore it is jsx_  kind of I don't know what you have in mind right now...  should go away as soon as you do something with your controls.
BUT if you start with a mapping that does not include the joystick assignment then you have to assign the joysticks to a certain number else they remain jsx_ as in your example.
Can also be seen in the Joystick Tab - jsN - Assignment  - your's is not assigned - should be js1 (or js2 for the second one)

Hope it helps - else just call in again

**Comment by d2bishop** [comment]
Just came back from trying to buy an older motorhome, it was all a scam did not buy :(
Thanks for input trying above.

**Comment by d2bishop** [comment]
Wow, works great both with and without CH Manager software.
Thanks bunches!!!
