### ISSUE TITLE
How to use de switch Mode (M1, M2 S1) of an X56 

### ISSUE THREAD

**Issue by LeChatFantome** [SCToolsfactory/SCJMapper-V2#73]
How to use the switching mode (M1, M2 S1) of an X56?

Hello, first a big thank you to you for all the work done!
Your job makes life much easier for many citizens!
In a word: Wonderful

I have a problem with the change of mode of the "Throttle" Joystick X56 -> M1, M2, S2

How can I use this feature in your software ?

Another big thank you to you !
![saitek-logitech-x-56-rhino-20](https://user-images.githubusercontent.com/40760882/42160328-15ab4d2e-7df7-11e8-90ae-5af7c20e08fe.jpg)

**Comment by bm98** [comment]
Hi and thank you for the nice words..
For your question - I could not figure out any use - have a similar one (X65F) and also such a mode switch.
It works with the Saitek software to program different commands for the modes - so you would need a set of alternate keyboard action mappings for the ones you want to use but not available in the games default map (such as your commands in SC are all e.g. LeftAlt and then something) and then map them in the Saitek SW - but this is quite a lot of work with SCs ever changing actions.. and it works only with buttons but not sliders or axes - the ones you can map into keyboard commands.

**Comment by LeChatFantome** [comment]
Hello, thank you for your very quick answer!
Sorry, for my slow response, really busy right now!

Yes the use of the switch mode button will be able to change the complete set up (Example: fighting mode in mode minnier or race mode)

or simply start the ship as a key (not detected).

Another question is, is it possible to add macro function (s)?

I think among other things the firing rate with the semi-automatic weapon.
1 press on the fire clic -> infinit clic 

Thank you for the time you are taking!

**Comment by bm98** [comment]
You may see my comment on #70 - it is about the same topic.
However the mode switches are usually captured by gamedriver.
Therefore you need to use the Saitek software and go through keyboard commands.
There you can do also Macros and such stuff. I am not aware that the mode switches can be released as regular button presses through the device driver or program.

**Comment by LeChatFantome** [comment]
Thank you very much !

I wish you a good continuation in your project!

See you soon in the universe
