### ISSUE TITLE
UI design feedback

### ISSUE THREAD

**Issue by harf4ng** [SCToolsfactory/SCJMapper-V2#74]
Hi,
On my computer I have like 10 joysticks. And I only use two, the vjoy ones.
So my UI is a little cluttered by all those sticks.
That would be great if SCJMapper could hide the tabs of the sticks we deactivated in the app config.
Also, that would be nice if we could customize the color of the different sticks.
Thanks

**Comment by bm98** [comment]
that sounds like a serious cockpit..
Yes I heard that request before and may see if I can get it into the next version.
Colors are more tricky - but let's see

**Comment by harf4ng** [comment]
Indeed, in fact I have a racing wheel, racing pedals, two warthog force sensitive sticks (from real simulator), a warthog throttle, MFG crosswind pedals, an helicopter cyclic, and two vjoy devices.
I use only the two vjoy devices in sttar citizen, with joystick gremlin.
Look, this is how it looks...
![20180331_100440](https://user-images.githubusercontent.com/22551859/42409364-a8c8d302-81d9-11e8-8540-006124cbb3a2.jpg)

**Comment by harf4ng** [comment]
Oh and btw thanks for your answer and your software, it is an amazing one.
My issue with colors is that sometimes colors are too pale and we can't easily see them in comparison with white color.
Look. In this screen, sticks 5 and 7 have colors too pale to see them, they are near white...
![stick color](https://user-images.githubusercontent.com/22551859/42409392-186b4bc2-81da-11e8-880a-89a0c2601baf.jpg)

**Comment by harf4ng** [comment]
I have found a workaround with this software:
https://github.com/briankendall/devreorder

With it I can hide all my physical controllers from scj mapper, and only shows the vjoy ones. And then I have only two tabs, and as I just have two tabs, the first is green, the second is blue, so it is viewable...

**Comment by bm98** [comment]
This is in testing right now - hiding and applying your own color
I got this request by others and if you don't want to hide the rest of your controls it will help as well.
And... yes this is a serious cockpit 🥇

**Comment by bm98** [comment]
Should be in the newest release - I close this one therefore
