### ISSUE TITLE
This is not an issue.

### ISSUE THREAD

**Issue by TyanColte** [SCToolsfactory/SCJMapper-V2#82]
This is not an issue. This is the only way I can figure to say THANK YOU SO VERY MUCH FOR CREATING THIS. This problem has plagued me every since I started playing Star Citizen. I can't believe I haven't stumbled across this little gem before since I've been struggling with this for a couple years now, but I'm so glad I found it now. This saves me hours of headache remapping all my controls every time my device ID changes. I really hope CIG and RSI fix the device enumeration system in the game to enumerate devices by their names instead of the ID windows gives it which will unfortunately make this app unnecessary but for now I have this little baby and my life has just gotten a ton easier. Thank you again so very much for creating it.

**Comment by bm98** [comment]
Opps. I am late, but thank you ... glad it helped out :)
