### ISSUE TITLE
Trying to rebuild source

### ISSUE THREAD

**Issue by davidbuckleyni** [SCToolsfactory/SCJMapper-V2#84]
Dude your source check-in is very messy trying rebuild getting an error on the hand.

    // Set the cooperative level for the device.
        m_device.SetCooperativeLevel(m_hwnd, CooperativeLevel.NonExclusive | CooperativeLevel.Background );
    

Out of the box it says

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1503	Argument 1: cannot convert from 'System.Windows.Forms.Control' to 'System.IntPtr'	SCJMapper-V2	C:\Users\David\Downloads\SCJMapper-V2-2.38beta\SCJMapper-V2-2.38beta\Devices\Joystick\JoystickCls.cs	507	Active

**Comment by bm98** [comment]
Dude, your version of DXsharp is possibly not the one mentioned in read me…

**Comment by bm98** [comment]
Seems to work ?
