### ISSUE TITLE
Layout dialogue

### ISSUE THREAD

**Issue by iNgeon** [SCToolsfactory/SCJMapper-V2#92]
Kudos on the layout option.
Any plans to add T.16000M FCS HOTAS mapping diagram
https://support.thrustmaster.com/en/product/t-16000m-fcs-hotas-en/

https://inovaestudios.blob.core.windows.net/forumsavatars/original/3X/7/8/784dfe325bd876956c5f017e0fbfa1b85c4b2800.jpg

https://i.redd.it/g70jsqvhhsiy.png

**Comment by bm98** [comment]
It is there but not properly formatted.. my bad
Replace the JSON file in the layouts folder with the one attached here (unzip first)
[t16000mfcs.zip](https://github.com/SCToolsfactory/SCJMapper-V2/files/4301942/t16000mfcs.zip)

**Comment by iNgeon** [comment]
Thank you, more people need to realize this great apps potential
