### ISSUE TITLE
Naming convention

### ISSUE THREAD

**Issue by sutex** [SCToolsfactory/SCJMapper-V2#93]
Have question up at spectrum but didn't want to add more to that thread

Any chance the naming convention used (in green) can be copied to paste into a search or a tool tip to semi explain what it is, in relation to the options in SC or link to a wiki?

example: 
v_weapon_cycle_aimmode  - assume that's the lag and lead toggle ?
v_weapon_toggle_ai   - gimbal/s?

**Comment by bm98** [comment]
Not really... such link would be outdated in a minute and create potential security issues - I cannot link to un-trusted sources... 
You can always Enable the CIG labels in Setting - this is more explanatory than the v_ names.
Profile Language: english (not profile)
