### ISSUE TITLE
Find 1st

### ISSUE THREAD

**Issue by sutex** [SCToolsfactory/SCJMapper-V2#96]
When clicking  js1_button1(trigger) on stick and then clicking on "Find 1st" it shows  js1_button11

![2020-05-06 11_55_01-SC Joystick Mapper](https://user-images.githubusercontent.com/10361359/81133344-79d0a180-8f90-11ea-93cb-d26a9090da12.png)

Note: also found it happening to button 3 "Find 1st" is showing Button 33

**Comment by bm98** [comment]
That is why it is called find 1st. 
It is a text search and it looks for the first occurrence of the text string "js1_button1"  and  js1_button11 starts with "js1_button1" (it finds everything starting with "js1_button1")
May be a later release will get a 'real' find for the DevCtrl but it is not priority right now.

**Comment by sutex** [comment]
Strange I didn't notice it doing that on previous releases
