### ISSUE TITLE
Show Layout Dialogue Throttle Bindings appear blank (T.16000M FCS Joystick & Throttle)

### ISSUE THREAD

**Issue by iNgeon** [SCToolsfactory/SCJMapper-V2#99]
Configure and setup my config
Show Layout Dialogue
Have to change layout setting to font size 12
Run wizard
The three HAT switched on the Throttle all show as blank even though they are configured ?

Also any plans to use dynamic scaling of the font for maximum readable size ?
Any plans to have dynamic scaling on the individual dialogue boxes and my setup which i dont find that hectic is hard to read (as im typing this it sounds like a lot of work... lol)

Side note
Updated Star Citizen to 3.10
Purge and redownload and SCJmapper
Reset Defaults and configure my presets

[layout_my_joystick2_3.10.0_ingeon.xml.txt](https://github.com/SCToolsfactory/SCJMapper-V2/files/5086133/layout_my_joystick2_3.10.0_ingeon.xml.txt)
![SCJmapper-T 16000mJoystick-Throttle-TestItemList](https://user-images.githubusercontent.com/3817692/90430529-e565f700-e0c7-11ea-897b-3e6d217ff1bf.png)
![SCJmapper-T 16000mJoystick-iNgeon-3 10](https://user-images.githubusercontent.com/3817692/90430541-e9921480-e0c7-11ea-8b42-9d0b88f18c55.png)

**Comment by Tsudico** [comment]
If the bindings for the HATs are within the "spaceship_targeting_advanced" section of the tree, it doesn't appear that has been added yet to SCJMapper so none of those bindings will show up in the layout, see #100 for more information.

**Comment by bm98** [comment]
See comment on #100 (need of update)
and no there is no plan to draw and scale fields according to usage.

**Comment by bm98** [comment]
Should be fixed in V2.48 Release
